<?php
 namespace app\models;

 use yii\base\Model;

 class ScoreForm extends Model{

     public $user_id;
     public $score;

     public function rules()
     {
         return
             [
                 ['score','required']
             ]; // TODO: Change the autogenerated stub
     }

 }