<?php

namespace app\models;

use yii\base\Model;

class UserForm extends Model {

    public $login;
    public $password;
    public $status;

    public function rules()
    {
        return [
            ['password','password']
        ]; // TODO: Change the autogenerated stub
    }

}